import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../config/theme/app_text_styles.dart';

import '../../domain/entities/transaction_entity.dart';
import '../bloc/transaction_bloc.dart';
import '../bloc/transaction_event.dart';
import '../../../categories/presentation/bloc/category_bloc.dart';
import '../../../categories/presentation/bloc/category_state.dart';
import '../../../categories/presentation/bloc/category_event.dart';

class AddTransactionSheet extends StatefulWidget {
  const AddTransactionSheet({super.key});

  static void show(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => const AddTransactionSheet(),
    );
  }

  @override
  State<AddTransactionSheet> createState() => _AddTransactionSheetState();
}

class _AddTransactionSheetState extends State<AddTransactionSheet> {
  bool _isExpense = true;
  final _titleController = TextEditingController();
  final _amountController = TextEditingController();
  String? _selectedCategoryId;

  @override
  void initState() {
    super.initState();
    context.read<CategoryBloc>().add(LoadCategoriesEvent());
  }

  @override
  void dispose() {
    _titleController.dispose();
    _amountController.dispose();
    super.dispose();
  }

  void _onSave() {
    final title = _titleController.text.trim();
    final amountText = _amountController.text.trim();
    
    if (title.isEmpty || amountText.isEmpty || _selectedCategoryId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill all fields and select a category')),
      );
      return;
    }

    final amount = double.tryParse(amountText);
    if (amount == null || amount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a valid positive amount')),
      );
      return;
    }

    final transaction = TransactionEntity(
      id: '', // Will be generated by repo
      amount: amount,
      note: title,
      type: _isExpense ? 'debit' : 'credit',
      categoryId: _selectedCategoryId!,
      timestamp: DateTime.now(),
    );

    context.read<TransactionBloc>().add(AddTransactionEvent(transaction));
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    // Bottom padding for keyboard
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;
    
    const Color greenColor = Color(0xFF1CB43E);
    const Color inputBackground = Color(0xFF2A2A2A);
    const Color blueColor = Color(0xFF3B38D0);

    return Container(
      padding: EdgeInsets.only(bottom: bottomInset, left: 24, right: 24, top: 24),
      decoration: const BoxDecoration(
        color: Color(0xFF1E1E1E),
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('Add Transaction', style: AppTextStyles.title.copyWith(color: Colors.white, fontSize: 20)),
                GestureDetector(
                  onTap: () => Navigator.of(context).pop(),
                  child: Text('Close', style: AppTextStyles.body.copyWith(color: Colors.white)),
                ),
              ],
            ),
            const SizedBox(height: 24),
            // Type Toggle
            Container(
              decoration: BoxDecoration(
                color: const Color(0xFF141414),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
              ),
              child: Row(
                children: [
                  Expanded(
                    child: GestureDetector(
                      onTap: () => setState(() => _isExpense = true),
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        decoration: BoxDecoration(
                          color: _isExpense ? greenColor : Colors.transparent,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        alignment: Alignment.center,
                        child: Text(
                          'Expense',
                          style: AppTextStyles.button.copyWith(color: Colors.white),
                        ),
                      ),
                    ),
                  ),
                  Expanded(
                    child: GestureDetector(
                      onTap: () => setState(() => _isExpense = false),
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        decoration: BoxDecoration(
                          color: !_isExpense ? greenColor : Colors.transparent,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        alignment: Alignment.center,
                        child: Text(
                          'Income',
                          style: AppTextStyles.button.copyWith(
                            color: !_isExpense ? Colors.white : Colors.white.withValues(alpha: 0.7),
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            // Title Input
            _buildInputField('Title', _titleController, inputBackground),
            const SizedBox(height: 16),
            // Amount Input
            _buildInputField('Amount ( ₹ )', _amountController, inputBackground, isNumber: true),
            const SizedBox(height: 24),
            // Category Selection
            Text('CATEGORY', style: AppTextStyles.caption.copyWith(color: Colors.white54)),
            const SizedBox(height: 12),
            BlocBuilder<CategoryBloc, CategoryState>(
              builder: (context, state) {
                if (state is CategoryLoading) {
                  return const LinearProgressIndicator();
                } else if (state is CategoryLoaded) {
                  if (state.categories.isEmpty) {
                    return Text('No categories found. Add from Profile.', style: AppTextStyles.body.copyWith(color: Colors.white54));
                  }
                  return SingleChildScrollView(
                    scrollDirection: Axis.horizontal,
                    child: Row(
                      children: state.categories.map((cat) {
                        final isSelected = _selectedCategoryId == cat.id;
                        return GestureDetector(
                          onTap: () => setState(() => _selectedCategoryId = cat.id),
                          child: Container(
                            margin: const EdgeInsets.only(right: 8),
                            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                            decoration: BoxDecoration(
                              color: isSelected ? blueColor.withValues(alpha: 0.2) : Colors.transparent,
                              borderRadius: BorderRadius.circular(8),
                              border: Border.all(
                                color: isSelected ? blueColor : Colors.white.withValues(alpha: 0.2),
                              ),
                            ),
                            child: Text(
                              cat.name,
                              style: AppTextStyles.body.copyWith(color: Colors.white),
                            ),
                          ),
                        );
                      }).toList(),
                    ),
                  );
                }
                return const SizedBox.shrink();
              },
            ),
            const SizedBox(height: 24),
            // Helper Text
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: const Color(0xFF132915), // Dark green tint
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                children: [
                   const Icon(Icons.info_outline, color: Colors.white, size: 16),
                   const SizedBox(width: 8),
                   Expanded(
                     child: Text(
                       'Everything you add here is saved only on your device.',
                       style: AppTextStyles.caption.copyWith(color: Colors.white),
                     ),
                   ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            // Save Button
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: blueColor,
                minimumSize: const Size(double.infinity, 56),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              ),
              onPressed: _onSave,
              child: Text('Save', style: AppTextStyles.button.copyWith(color: Colors.white)),
            ),
            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }

  Widget _buildInputField(String hint, TextEditingController controller, Color bg, {bool isNumber = false}) {
    return Container(
      decoration: BoxDecoration(
        color: bg,
        borderRadius: BorderRadius.circular(8),
      ),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
      child: TextField(
        controller: controller,
        autocorrect: false,
        enableSuggestions: false,
        cursorColor: Colors.white,
        keyboardType: isNumber ? const TextInputType.numberWithOptions(decimal: true) : TextInputType.text,
        style: const TextStyle(color: Colors.white, fontSize: 16),
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: TextStyle(color: Colors.white.withValues(alpha: 0.4)),
          filled: true,
          fillColor: Colors.transparent,
          border: InputBorder.none,
          enabledBorder: InputBorder.none,
          focusedBorder: InputBorder.none,
        ),
      ),
    );
  }
}
